name: ETL pipeline demo

on:
    push:
        branches:
            - main

jobs:
    extract-data-job:
        runs-on: ubuntu-latest  
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: run extract.py
              run: python --version
    transform-data-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: action/checkout@v2

            - name: run transform.py
              run: python --version

    load-data-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: action/checkout@v2

            - name: run load.py
              run: python --version

            

